feat: improve usage function

diff --git a/yt-dlpp b/yt-dlpp
--- a/yt-dlpp
+++ b/yt-dlpp
@@ -52,7 +52,12 @@ is_true() {
 
 # shellcheck disable=SC2120
 usage() {
-    _assert_no_params "$@"
+    local exitcode=0
+    if [[ "$#" -ne 0 ]]; then
+        local exitcode=64
+        echo "Error: $*"
+    fi
+    readonly exitcode
     cat <<EOF
 Usage: $(basename "$0") [COMMAND] [URL] [PATH]
 Commands:
@@ -72,7 +77,7 @@ Environment variables:
   RETRY_MAX_ATTEMPTS      Max retry attempts (default: 3)
   RETRY_BACKOFF           Retry backoff time (default: 1s)
 EOF
-    exit 0
+    exit "$exitcode"
 }
 
 filesize() {
@@ -96,13 +101,21 @@ with_retry() {
     local -r max_attempts="${RETRY_MAX_ATTEMPTS-3}"
     local -r backoff="${RETRY_BACKOFF-"1s"}"
     local attempt=1
+    local last_errcode=1
     while [[ $attempt -le "$max_attempts" ]]; do
-        if "$@"; then return 0; fi
-        attempt=$((attempt + 1))
-        echo "Warning: Retrying in $backoff (attempt $attempt out of $max_attempts)" >&2
-        sleep "$backoff"
+        if "$@"; then
+            return
+        else
+            last_errcode="$?"
+            if [[ "$last_errcode" == 64 ]]; then
+                exit "$last_errcode"
+            fi
+            attempt=$((attempt + 1))
+            echo "Warning: command exits with code $last_errcode. Retrying in $backoff (attempt $attempt out of $max_attempts)" >&2
+            sleep "$backoff"
+        fi
     done
-    return 1
+    return "$last_errcode"
 }
 
 yt_dlp_wrapper() {
@@ -488,7 +501,7 @@ d | download)
         readonly url="$1"
         shift
     else
-        usage
+        usage "URL is required for download mode"
     fi
     if [[ "$#" -ge 1 ]]; then
         readonly dir="$1"
@@ -497,7 +510,7 @@ d | download)
         readonly dir="."
     fi
     if [[ "$#" -ge 1 ]]; then
-        usage
+        usage "Too many arguments for download mode"
     fi
 
     download_mode "$url" "$dir"
@@ -506,6 +519,8 @@ a | audio)
     if [[ "$#" -ge 1 ]]; then
         readonly url="$1"
         shift
+    else
+        usage "URL is required for audio mode"
     fi
     if [[ "$#" -ge 1 ]]; then
         readonly dir="$1"
@@ -514,7 +529,7 @@ a | audio)
         readonly dir="."
     fi
     if [[ "$#" -ge 1 ]]; then
-        usage
+        usage "Too many arguments for audio mode"
     fi
 
     audio_mode "$url" "$dir"
@@ -523,9 +538,11 @@ v | update-video)
     if [[ "$#" -ge 1 ]]; then
         readonly path="$1"
         shift
+    else
+        usage "Path is required for update-video mode"
     fi
     if [[ "$#" -ge 1 ]]; then
-        usage
+        usage "Too many arguments for update-video mode"
     fi
 
     update_video_mode "$path"
@@ -534,9 +551,11 @@ u | update-danmaku)
     if [[ "$#" -ge 1 ]]; then
         readonly path="$1"
         shift
+    else
+        usage "Path is required for update-danmaku mode"
     fi
     if [[ "$#" -ge 1 ]]; then
-        usage
+        usage "Too many arguments for update-danmaku mode"
     fi
 
     update_danmaku_mode "$path"
@@ -545,6 +564,6 @@ h | help)
     usage
     ;;
 *)
-    usage
+    usage "Unknown command: $command"
     ;;
 esac
